sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: chenyanxi609
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tE381wqZCseHggM2SYD
    access-key-secret: irKbPYIo6tAmotrAbC45sZ40gmt2nG
    bucket-name: cenci